# Port du serveur Spring Boot (8080 par défaut)
server.port=8080

# Configuration de la base de données MySQL
spring.datasource.url=jdbc:mysql://linserv-info-01.campus.unice.fr:3306/ld401629_five_nights_at_fabron?serverTimezone=UTC
spring.datasource.username=ld401629
spring.datasource.password=ld401629
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# FORCER LE DIALECTE : Empêche Hibernate de planter s'il n'arrive pas à lire les métadonnées
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Hibernate : Met à jour la structure de la base automatiquement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true